config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  
  validates :name, :weigth, :width, :height, :depth, :sku, presence: true
  validates :sku, uniqueness: true
  validates :sku, length: { is: 20 }
  validates :weigth, :width, :height, :depth, comparison: {greater_than: 0 }
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :weigth, :width, :height, :depth, :sku, :supplier_id)
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/views/product_models/index.html.erb
<h1> Modelos de Produtos </h1>

<%= link_to 'Cadastrar Novo', new_product_model_url %>

<% if @product_models.any? %>
 <% @product_models.each do |pm| %>
   <div>
     <h2> <%= pm.name %> </h2>
     <dl>
     <dt> <strong> <%= ProductModel.human_attribute_name(:sku)%>: </strong> </dt>
     <dd> <%= pm.sku %> </dd>
     <dt> <strong> <%= ProductModel.human_attribute_name(:supplier_id)%>: </strong> </dt>
     <dd> <%= pm.supplier.brand_name %> </dd>
     </dl>
   </div>
  <% end %>
<% else %>
  <p> Nenhum modelo de produto cadastrado. </p>
<% end %>

app/views/product_models/new.html.erb
<h1> Cadastrar Novo <%= ProductModel.model_name.human %> </h1>

<% if @product_model.errors.any? %>
  <ul>
    <p> Verifique os erros abaixo: </p>
    <% @product_model.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>

<% end %>

<%= form_with model: @product_model do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :weigth %>
  <%= f.number_field :weigth %>
  </div>
  <div>
  <%= f.label :width %>
  <%= f.number_field :width %>
  </div>
  <div>
  <%= f.label :height %>
  <%= f.number_field :height %>
  </div>
  <div>
  <%= f.label :depth %>
  <%= f.number_field :depth %>
  </div>
  <div>
  <%= f.label :sku %>
  <%= f.text_field :sku %>
  </div>
  <div>
  <%= f.label :supplier_id %>
  <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>
  <%= f.submit %>
  <% end %>

  

app/views/product_models/show.html.erb
<h1> <%= @product_model.name %> </h1>

<dl>
<dt> <%= ProductModel.human_attribute_name(:supplier_id)%>: </dt>
<dd><%= @product_model.supplier.brand_name %></dd>
<dt> <%= ProductModel.human_attribute_name(:sku)%>: </dt>
<dd><%= @product_model.sku %></dd>
<dt> Dimensão: </dt>
<dd><%= @product_model.height %>cm x <%= @product_model.width %>cm x <%= @product_model.depth %>cm</dd>
<dt> <%= ProductModel.human_attribute_name(:weigth)%>: </dt>
<dd><%= @product_model.weigth %>g </dd>
</dl>