config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  validates :corporate_name, :brand_name, :registration_number, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, length: { is: 14 }
  validates :registration_number, numericality: { only_integer: true }

  def description
    "#{corporate_name} - CNPJ: #{registration_number[0..1]}.#{registration_number[2..4]}.#{registration_number[5..7]}/#{registration_number[8..11]}-#{registration_number[12..13]}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show
    @product_models = ProductModel.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:alert] = 'Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def edit;end

  def update
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso.'
    else
      flash.now[:alert] = 'Não foi possível atualizar o fornecedor.'
      render 'edit'
    end
  end

  private
  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
  end
end

app/views/suppliers/edit.html.erb
<h1> Editar <%= Supplier.model_name.human %> </h1>

<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_area :brand_name %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
  <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/index.html.erb
<h1> <%= Supplier.model_name.human %> </h1>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th> Nome </th>
        <th> Localização </th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |s| %>
        <tr>
          <td> <%= link_to s.brand_name, s %> </td>
          <td> <%= s.city %> - <%= s.state %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p> Não existem fornecedores cadastrados. </p>
<% end %>

<%= link_to 'Cadastrar novo fornecedor', new_supplier_url %>

app/views/suppliers/new.html.erb
<h1> Novo <%= Supplier.model_name.human %> </h1>

<% if @supplier.errors.any? %>
  <ul>
    <p> Verifique os erros abaixo: </p>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>

<% end %>

<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_area :brand_name %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
  <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/show.html.erb
<h1> <%= Supplier.model_name.human %> <%= @supplier.brand_name%> </h1>
<h2> <%= @supplier.corporate_name %> </h2>

<dl>
<dt> Documento: </dt>
<dd> <%= @supplier.registration_number[0..1] %>.<%= @supplier.registration_number[2..4] %>.<%= @supplier.registration_number[5..7] %>/<%= @supplier.registration_number[8..11] %>-<%= @supplier.registration_number[12..13] %> </dd>
<dt> <%= Supplier.human_attribute_name(:full_address)%>: </dt>
<dd> <%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %> </dd>
<dt> <%= Supplier.human_attribute_name(:email)%>: </dt>
<dd> <%= @supplier.email %> </dd>
</dl>

<%= link_to 'Editar', edit_supplier_url(@supplier) %>

<h2> Lista dos Modelos de Produtos Associados a <%= @supplier.brand_name%> </h2>

<% @product_models.each do |pm| %>
  <% if pm.supplier_id == @supplier.id %>
    <h3> <%= pm.name %> </h3>

    <dl>
    <dt> Dimensão: </dt>
    <dd><%= pm.height %>cm x <%= pm.width %>cm x <%= pm.depth %>cm</dd>
    <dt> <%= ProductModel.human_attribute_name(:sku)%>: </dt>
    <dd><%= pm.sku %></dd>
    </dl>
  <% end %>
<% end %>

<div>
  <%= link_to 'Voltar', root_url %>
</div>