config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

  <header>
    <%= link_to root_path do %>
      <h1>Galpões & Estoque</h1>
    <% end %>
    <nav>
      <%= link_to 'Fornecedores', suppliers_url %> |
      <%= link_to 'Modelos de Produtos', product_models_url %> |
      <%= link_to 'Registrar pedido', new_order_url %> |
      <%= link_to 'Meus Pedidos', orders_url %>
      
      <% if user_signed_in? %>
        <%= form_with url: search_orders_url, method: :get do |f| %>
         <%= f.label :query, 'Buscar Pedido' %>
          <%= f.text_field :query %>
          <%= f.submit 'Buscar' %>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <%= current_user.description %> |
        <%= button_to 'Sair', destroy_user_session_url, method: :delete %> 
      <% else %>
        <%= link_to 'Entrar', new_user_session_url %>
      <% end %>
    </nav>
  </header>
  <div>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
  </div>

  <main>
    <%= yield %>
  <main>
  
  </body>
</html>